factomWalletd:
  # Docker image repository
  image: factominc/factom-walletd

  # Docker image tag
  imageTag: latest

  # Container resource limits and requests
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

deployment:
  replicas: 1
